server:
  port: 19999

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19999/eureka/

spring:
  application:
    name: spring-cloud-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/
        prefix: /config
    stream:
      kafka:
        binder:
          brokers: 172.16.1.126,172.16.1.129
