server:
  port: 19999

spring:
  application:
    name: spring-cloud-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/
        prefix: /config # set the prefix of Config Server Rest API
    stream:
      kafka:
        binder:
          brokers: 172.16.1.126,172.16.1.129
  redis:
    host: 172.16.1.130

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19999/eureka/

zuul:
  sensitiveHeaders:
  routes:
    spring-cloud-client:
      path: /spring-cloud-client/**
      # sensitiveHeaders: Authorization
      # sensitiveHeaders: Cookie,Set-Cookie,Authorization
      # sensitive-headers: Authorization


lj:
  login-service-id: spring-cloud-client
