server:
  port: 10000

spring:
  application:
    name: spring-cloud-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/
        prefix: /config # set the prefix of Config Server Rest API
    stream:
      kafka:
        binder:
          brokers: 172.16.1.126,172.16.1.129
      bindings:
        output:
          destination: input
        customOutChannel1:
          destination: customInChannel1
        customOutChannel2:
          destination: customInChannel2
          # content-type: application/json
          # group: test
  redis:
    host: 172.16.1.130

zuul:
  sensitiveHeaders: # keep all sensitive headers
  routes:
    spring-cloud-client:
      path: /spring-cloud-client/**
      # sensitiveHeaders: Cookie,Set-Cookie,Authorization

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/



lj:
  login-service-id: spring-cloud-client
