test:
  config: "test-config..."
  name: "test-name-test"
  name1: "test-name-1"
  name2: "test-name-2"

server:
  port: 20001

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 172.16.1.126,172.16.1.129
    bus:
      id: ${vcap.application.name:${spring.application.name:application}}:${vcap.application.instance_index:${spring.profiles.active:${local.server.port:${server.port:0}}}}:${vcap.application.instance_id:${random.value}}
  redis:
    host: 172.16.1.130
